// <auto-generated />
using System;
using Infrastructure.Persistence;
using Infrastructure.Persistence.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ActionRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComparisonType")
                        .HasColumnType("integer");

                    b.Property<string>("ComparisonValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSchedule")
                        .HasColumnType("boolean");

                    b.Property<string>("MeasureProperty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OutletAction")
                        .HasColumnType("integer");

                    b.Property<int>("OutletConfigurationId")
                        .HasColumnType("integer");

                    b.Property<int?>("ScheduledTimeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("OutletConfigurationId");

                    b.HasIndex("ScheduledTimeId");

                    b.ToTable("ActionRules");
                });

            modelBuilder.Entity("Domain.Entities.EnvironmentMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("GroundHumidity")
                        .HasColumnType("double precision");

                    b.Property<double>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<double>("Pressure")
                        .HasColumnType("double precision");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Measures");
                });

            modelBuilder.Entity("Domain.Entities.OutletConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("OutletId")
                        .HasColumnType("integer");

                    b.Property<int>("PinId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("OutletId")
                        .IsUnique();

                    b.ToTable("OutletConfigurations");
                });

            modelBuilder.Entity("Domain.Entities.ScheduledTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Hour")
                        .HasColumnType("integer");

                    b.Property<int>("Minute")
                        .HasColumnType("integer");

                    b.Property<int>("Second")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ScheduledTime");
                });

            modelBuilder.Entity("Domain.Entities.TakenAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionRuleId")
                        .HasColumnType("integer");

                    b.Property<int>("EnvironmentMeasureId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActionRuleId");

                    b.HasIndex("EnvironmentMeasureId");

                    b.ToTable("TakenActions");
                });

            modelBuilder.Entity("Domain.Entities.ActionRule", b =>
                {
                    b.HasOne("Domain.Entities.OutletConfiguration", "Outlet")
                        .WithMany()
                        .HasForeignKey("OutletConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ScheduledTime", "ScheduledTime")
                        .WithMany()
                        .HasForeignKey("ScheduledTimeId");

                    b.Navigation("Outlet");

                    b.Navigation("ScheduledTime");
                });

            modelBuilder.Entity("Domain.Entities.TakenAction", b =>
                {
                    b.HasOne("Domain.Entities.ActionRule", "ActionRule")
                        .WithMany()
                        .HasForeignKey("ActionRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.EnvironmentMeasure", "EnvironmentMeasure")
                        .WithMany()
                        .HasForeignKey("EnvironmentMeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionRule");

                    b.Navigation("EnvironmentMeasure");
                });
#pragma warning restore 612, 618
        }
    }
}
